package com.mitocode.jsf.model;

// Generated Feb 27, 2021, 9:56:04 AM by Hibernate Tools 5.4.27.Final

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codigo;
	private Producto producto;
	private Venta venta;
	private Byte cantidad;

	public DetalleVenta() {
	}

	public DetalleVenta(Producto producto, Venta venta, Byte cantidad) {
		this.producto = producto;
		this.venta = venta;
		this.cantidad = cantidad;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	public Byte getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Byte cantidad) {
		this.cantidad = cantidad;
	}

}
