package com.mitocode.jsf.model;

// Generated Feb 27, 2021, 9:56:04 AM by Hibernate Tools 5.4.27.Final

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte empCod;
	private User user;
	private String empNames;
	private String empLastNames;
	private Character empSex;

	public Employee() {
	}

	public Employee(User user) {
		this.user = user;
	}

	public Employee(User user, String empNames, String empLastNames, Character empSex) {
		this.user = user;
		this.empNames = empNames;
		this.empLastNames = empLastNames;
		this.empSex = empSex;
	}

	public byte getEmpCod() {
		return this.empCod;
	}

	public void setEmpCod(byte empCod) {
		this.empCod = empCod;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getEmpNames() {
		return this.empNames;
	}

	public void setEmpNames(String empNames) {
		this.empNames = empNames;
	}

	public String getEmpLastNames() {
		return this.empLastNames;
	}

	public void setEmpLastNames(String empLastNames) {
		this.empLastNames = empLastNames;
	}

	public Character getEmpSex() {
		return this.empSex;
	}

	public void setEmpSex(Character empSex) {
		this.empSex = empSex;
	}

}
