package com.mitocode.jsf.model;

// Generated Feb 27, 2021, 9:56:04 AM by Hibernate Tools 5.4.27.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codigo;
	private String nombre;
	private BigDecimal precio;
	private Set detalleVentas = new HashSet(0);

	public Producto() {
	}

	public Producto(String nombre, BigDecimal precio) {
		this.nombre = nombre;
		this.precio = precio;
	}

	public Producto(String nombre, BigDecimal precio, Set detalleVentas) {
		this.nombre = nombre;
		this.precio = precio;
		this.detalleVentas = detalleVentas;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Set getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

}
