package com.mitocode.jsf.model;

// default package
// Generated Feb 27, 2021, 9:56:04 AM by Hibernate Tools 5.4.27.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Byte usCode;
	private String usName;
	private String usPassword;
	private Employee employee;
	private Student student;

	public User() {
	}

	public User(String usName, String usPassword, Employee employee, Student student) {
		this.usName = usName;
		this.usPassword = usPassword;
		this.employee = employee;
		this.student = student;
	}

	public Byte getUsCode() {
		return this.usCode;
	}

	public void setUsCode(Byte usCode) {
		this.usCode = usCode;
	}

	public String getUsName() {
		return this.usName;
	}

	public void setUsName(String usName) {
		this.usName = usName;
	}

	public String getUsPassword() {
		return this.usPassword;
	}

	public void setUsPassword(String usPassword) {
		this.usPassword = usPassword;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
