package com.mitocode.jsf.model;

// default package
// Generated Feb 27, 2021, 9:56:04 AM by Hibernate Tools 5.4.27.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer codigo;
	private Persona_ persona;
	private Date fecha;
	private BigDecimal monto;
	private Set detalleVentas = new HashSet(0);

	public Venta() {
	}

	public Venta(Persona_ persona, Date fecha, BigDecimal monto, Set detalleVentas) {
		this.persona = persona;
		this.fecha = fecha;
		this.monto = monto;
		this.detalleVentas = detalleVentas;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Persona_ getPersona() {
		return this.persona;
	}

	public void setPersona(Persona_ persona) {
		this.persona = persona;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public Set getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

}
